---
title: Resources
layout: default
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}

.navbar-collapse.in {
  display: block !important;
}
</style>

<br/>
<br/>


# **Organizations**

### [R-Project](https://www.r-project.org/) - *a free software environment for statistical computing and graphics*
### [CRAN](https://cran.r-project.org/) - *a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R*
### [R Consortium](https://www.r-consortium.org/) - *group organized to support the worldwide community of users, maintainers and developers of R software*

---

# **Blogs / Docs**

### [R-Bloggers](https://www.r-bloggers.com/) - *blog aggregator of content contributed by bloggers who write about R*
### [Revolutions](http://blog.revolutionanalytics.com/) - *blog dedicated to news and information of interest to members of the R community*
### [RDocumentation](https://www.rdocumentation.org/) - *search portal of all 15,000+ CRAN, Bioconductor and GitHub packages*

---

# **Community**

### [Meetup R User Group](https://www.meetup.com/pro/r-user-groups) - *worldwide network of R User Groups that have been sponsored by the R Consortium*
### [GitHub R Trending](https://github.com/trending/r) - *currently trending R repositories*
### [StackOverflow R Tag](https://stackoverflow.com/questions/tagged/r) - *tag used for the 250,000+ programming-related questions about R*

